### PR TITLE
fix: correct commandline when running in docker

### PR DESCRIPTION
**Pull request by iain-anderson**
fixes: #69

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-bacnet-c/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  (includes in-repo doc update)

### CODE REVIEW

**Review by bnevis-i — APPROVED** [review]

**Comment by iain-anderson** [comment]
@jheddings can you confirm that the service works for you with this change?

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by jheddings** [comment]
The docker image is building fine and running...  I'm working through an issue with getting the configuration uploaded during startup.

The logs show:
```
level=INFO ts=2022-11-30T16:34:16Z app=device-bacnet-ip msg="Uploading configuration to registry."
level=ERROR ts=2022-11-30T16:34:16Z app=device-bacnet-ip msg="Unable to upload config: HTTP request failed"
Error: 21: HTTP request failed
edgex-device-bacnet exited with code 21
```

And there is a log around the same time from the consul service:
```
2022-11-30T16:34:17.635Z [ERROR] agent.http: Request error: method=PUT url=/v1/txn from=172.21.0.12:50860 error="Transaction contains too many operations (65 > 64)"
```

I'm using the compose file generated by `compose-builder` (no security), which uses the following config (updated to use the built `-dev` image):
```
  device-bacnet:
    container_name: edgex-device-bacnet
    depends_on:
    - consul
    - data
    - metadata
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-device-bacnet
    hostname: edgex-device-bacnet
    image: docker.io/edgexfoundry/device-bacnet:2.3.0-dev
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:59980:59980/tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
```

**Comment by iain-anderson** [comment]
@jheddings ok, I'm going to merge this, and then create another PR for the consul issue.
Consul has a hardcoded limit on the size of the configuration set to be uploaded in a transaction - going forward this should be handled in the SDK but for now I think we can reduce the config size by the 1 item necessary

**Pull request merged**
