### PR TITLE
update Jenkinsfile to use Fuji style

### PR DESCRIPTION
**Pull request by ernestojeda**
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

### CODE REVIEW

**Comment by ernestojeda** [comment]
Working sandbox job here:
https://jenkins.edgexfoundry.org/sandbox/view/All/job/fuji-device-bacnet-c-verify-pipeline/1/console

**Comment by jamesrgregg** [comment]
@iain-anderson please review

**Comment by jamesrgregg** [comment]
@lranjbar please weigh in here as this service although versioned independently was slated for FUJI, not EDINBURGH release so I"m not following the need to version as 1.0.0 as @iain-anderson suggests.

**Comment by iain-anderson** [comment]
The service as it stands builds against the Edinburgh version of the SDK and advertises itself as version 1.0.0.
So we could either
Release as is with 1.0.0, make an edinburgh branch, then move everything to 1.1.0
or
If we are ok waiting another few weeks, forget about 1.0 and move the codebase forward now

If we are doing the latter, this PR is fine

**Comment by tonyespy** [comment]
As Fuji is just a minor release of the 1.x, there's no need to align the version of this service with Fuji's version. The rules for application and device service is that the major version needs to align with the compatible major version of EdgeX, but that minor and/or patch releases aren't tied to specific minor or patch releases of EdgeX.

One other question, it looks like the build environment has been changed from Alpine to CentOS, are we sure that there aren't any libc compatibility issues building the artifacts on CentOS and running in an Alpine-based container?

**Comment by lranjbar** [comment]
I talked to Iain on slack and to verify for device-bacnet-c we are going to release a 1.0.0 version for Edinburgh first. After this PR is merged we need to cut the edinburgh branch. Changes after this release will be to verify the service is compatible with the Fuji release. Due to timing this will happen after the main Fuji release.

**Comment by iain-anderson** [comment]
Isn't it that we are building in an Alpine container running on a Centos host?

**Comment by jamesrgregg** [comment]
@iain-anderson that's correct. this builds two images but uses two different hosts (VMs) - one Centos x-86 and the other Ubuntu-ARM64

**Comment by ernestojeda** [comment]
> Isn't it that we are building in an Alpine container running on a Centos host?

Yes, we are actually building an x86_64 image and an arm64 image like we do for all the other projects.

Here are the agent declarations:
https://github.com/edgexfoundry/device-bacnet-c/pull/26/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3R42
https://github.com/edgexfoundry/device-bacnet-c/pull/26/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3R71

**Pull request merged**
